apiVersion: v1
kind: ConfigMap
data:
  #KAFKA_SERVER: kafka-cluster-kafka-0.kafka.svc.cluster.local:9092
  KAFKA_SERVER: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  KAFKA_TOPIC: location
  DB_USERNAME: "ct_location"
  DB_NAME: "locations"
  DB_HOST: "postgres-db-locations"
  DB_PORT: "5432"
metadata:
  name: kafka-location-cm