apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locations-kafka-api
  name: udaconnect-locations-kafka-api
spec:
  ports:
  - port: 5005
    targetPort: 5005
    nodePort: 30004
  selector:
    service: udaconnect-locations-kafka-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locations-kafka-api
  name: udaconnect-locations-kafka-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locations-kafka-api
  template:
    metadata:
      labels:
        service: udaconnect-locations-kafka-api
    spec:
      containers:
      - image: queryinterface/nd064-locations-kafka-producer:latest
        name: udaconnect-locations-api
        imagePullPolicy: Always
        env:
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-location-cm
              key: KAFKA_SERVER
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-location-cm
              key: KAFKA_TOPIC
      restartPolicy: Always
