apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connections-api
  name: udaconnect-connections-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: udaconnect-connections-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connections-api
  name: udaconnect-connections-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connections-api
  template:
    metadata:
      labels:
        service: udaconnect-connections-api
    spec:
      containers:
      - image: queryinterface/nd064-connections-api:latest
        name: udaconnect-connections-api
        imagePullPolicy: Always
        env:
        - name: PERSON_SERVICE_API_URL
          valueFrom:
            configMapKeyRef:
              name: connections-cm
              key: PERSON_SERVICE_API_URL
        - name: LOCATION_SERVICE_API_URL
          valueFrom:
            configMapKeyRef:
              name: connections-cm
              key: LOCATION_SERVICE_API_URL
      restartPolicy: Always
